# CodeRabbit Configuration for Coding Match Platform
# https://docs.coderabbit.ai/guides/configure-coderabbit

# Language and tone
language: en-US
tone_instructions: "Be concise, technical, and focus on best practices for real-time collaborative applications, TypeScript, React, and Convex backend."

# Review settings
reviews:
  # High-level summary of changes
  high_level_summary: true
  
  # Detailed poem-style summary (disable for more serious reviews)
  poem: false
  
  # Review levels: "simple" (faster) or "detailed" (thorough)
  review_status: detailed
  
  # Auto-approve minor changes
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
  
  # Request changes for critical issues
  request_changes_workflow: true
  
  # Collapse details in review comments
  collapse_walkthrough: true

# Path-based instructions
path_instructions:
  - path: "convex/**/*.ts"
    instructions: |
      - Review Convex schema definitions, queries, mutations, and actions
      - Check for proper input validation using v.object()
      - Ensure indexes are optimal for query patterns
      - Verify auth checks are present where needed
      - Look for potential race conditions in mutations
      - Check for proper error handling
  
  - path: "**/*.tsx"
    instructions: |
      - Review React components for performance (useMemo, useCallback)
      - Check for proper TypeScript typing
      - Ensure hooks are used correctly
      - Look for accessibility issues (a11y)
      - Verify error boundaries are in place
      - Check for memory leaks (cleanup in useEffect)
  
  - path: "**/*.ts"
    instructions: |
      - Review TypeScript code for type safety
      - Check for proper error handling
      - Look for potential null/undefined issues
      - Verify async/await usage is correct
      - Check for security vulnerabilities
  
  - path: "**/components/**"
    instructions: |
      - Review component architecture and reusability
      - Check for prop drilling issues
      - Verify component composition patterns
      - Look for styling consistency (Tailwind usage)
      - Check responsive design considerations
  
  - path: "**/hooks/**"
    instructions: |
      - Review custom hooks for correctness
      - Check dependency arrays in useEffect/useMemo/useCallback
      - Verify hook return types are properly typed
      - Look for potential infinite loops
  
  - path: "**/lib/**"
    instructions: |
      - Review utility functions for edge cases
      - Check for proper input validation
      - Verify error handling
      - Look for performance optimization opportunities
  
  - path: "**/*.test.ts"
    instructions: |
      - Review test coverage and quality
      - Check for edge cases
      - Verify mocking is done correctly
      - Look for flaky tests
      - Ensure tests are maintainable

# Chat settings
chat:
  auto_reply: true

# Knowledge base for context
knowledge_base:
  # Coding platform specific patterns
  learnings:
    - "This is a real-time coding match platform where users compete by solving problems"
    - "Uses Convex for backend (realtime database, queries, mutations)"
    - "Real-time collaboration with cursor sharing and code synchronization"
    - "Payment integration with Autumn for paid matches"
    - "Match states: created -> started -> finished/cancelled"
    - "Events array stores all match activity (code changes, submissions, messages)"
  
  # Important patterns to watch for
  patterns:
    - "Always validate user IDs match the authenticated user in mutations"
    - "Use optimistic updates for real-time UI feedback"
    - "Debounce code editor changes before saving to avoid excessive writes"
    - "Handle race conditions in match state transitions"
    - "Implement proper cleanup in WebSocket/realtime subscriptions"

# Files to ignore
reviews:
  exclude_patterns:
    - "**/*.min.js"
    - "**/dist/**"
    - "**/build/**"
    - "**/.next/**"
    - "**/node_modules/**"
    - "**/*.lock"
    - "**/package-lock.json"
    - "**/yarn.lock"
    - "**/pnpm-lock.yaml"
    - "**/*.log"
    - "**/.env*"
    - "**/coverage/**"

# Enable specific checks
checks:
  # Code quality
  code_quality: true
  
  # Security vulnerabilities
  security: true
  
  # Performance issues
  performance: true
  
  # Best practices
  best_practices: true
  
  # Documentation
  documentation: true
  
  # Test coverage
  test_coverage: true

# Early access features
early_access: false

# Enable tools
tools:
  # AST-based analysis
  ast_grep:
    enabled: true
    
    # Custom rules for common issues
    rules:
      - id: "no-console-log"
        pattern: "console.log($$$)"
        message: "Remove console.log before committing"
        severity: "warning"
      
      - id: "use-convex-query"
        pattern: "useQuery($$$)"
        message: "Ensure useQuery is from 'convex/react'"
        severity: "info"
      
      - id: "auth-check-mutation"
        pattern: "export const $NAME = mutation($_)"
        message: "Ensure mutation includes auth check via ctx.auth"
        severity: "warning"

# Pull request settings
pull_requests:
  # Auto-label based on changes
  auto_label:
    enabled: true
    labels:
      - name: "convex"
        patterns: ["convex/**"]
      - name: "frontend"
        patterns: ["**/*.tsx", "components/**"]
      - name: "backend"
        patterns: ["convex/**/*.ts"]
      - name: "hooks"
        patterns: ["**/hooks/**"]
      - name: "types"
        patterns: ["**/*.d.ts", "**/types/**"]
      - name: "tests"
        patterns: ["**/*.test.ts", "**/*.test.tsx"]
      - name: "dependencies"
        patterns: ["package.json", "pnpm-lock.yaml"]

# Code review focus areas
focus_areas:
  - "Real-time synchronization correctness"
  - "Race condition handling"
  - "Authentication and authorization"
  - "Input validation"
  - "Error handling"
  - "Performance optimization"
  - "Type safety"
  - "Memory leak prevention"
  - "Security vulnerabilities"
  - "Accessibility (a11y)"